=== engsyst/ftua/FitnessUA/src/security.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ua.nure.ostpc.malibu.shedule/FitnessUA" xmlns:tns="http://ua.nure.ostpc.malibu.shedule/FitnessUA">

	<xsd:element name="security">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="constraint" type="tns:constraint"
					maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="constraint">
		<xsd:sequence>
			<xsd:element name="url-pattern" type="xsd:string" />
			<xsd:sequence>
				<xsd:element name="right" type="tns:right" minOccurs="0"
					maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="right" mixed="true" />

</xsd:schema>

=== engsyst/ftua/FitnessUA/src/security.xml
<?xml version="1.0" encoding="UTF-8"?>

<is:security xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:is="http://ua.nure.ostpc.malibu.shedule/FitnessUA"
	xsi:schemaLocation="http://ua.nure.ostpc.malibu.shedule/FitnessUA security.xsd">

	<constraint>
		<url-pattern>/login*</url-pattern>
		<right>responsible_person</right>
		<right>admin</right>
	</constraint>

	<constraint>
		<url-pattern>/logout*</url-pattern>
		<right>visitor</right>
	</constraint>

	<constraint>
		<url-pattern>/</url-pattern>
		<right>visitor</right>
	</constraint>

	<constraint>
		<url-pattern>/scheduleManager*</url-pattern>
		<right>visitor</right>
	</constraint>

	<constraint>
		<url-pattern>/excelEmployeeImport*</url-pattern>
		<right>admin</right>
		<right>visitor</right>
	</constraint>

	<constraint>
		<url-pattern>/excelEmployeeExport*</url-pattern>
		<right>admin</right>
		<right>visitor</right>
	</constraint>

	<constraint>
		<url-pattern>/error</url-pattern>
		<right>responsible_person</right>
		<right>admin</right>
		<right>visitor</right>
	</constraint>

	<constraint>
		<url-pattern>/error/</url-pattern>
		<right>responsible_person</right>
		<right>admin</right>
		<right>visitor</right>
	</constraint>

</is:security>
